### ISSUE TITLE
Mod Manager not exiting properly after a mod.ini error

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/SA-Mod-Manager#102]
If you place a `mod.ini` in the mods folder without putting it in a subfolder, the Mod Manager will identify the problem correctly and attempt to quit, but it fails to close and crashes with `System.NullReferenceException: 'Object reference not set to an instance of an object.'`. 

Also, looking at some recent error reports with SA2 mods I think it might be a good idea to make sure the `mod.ini` error check is also performed for SA2 mods.

**Comment by ItsEasyActually** [comment]
This appears to have been fixed at some point, but this issue wasn't closed. I'm unable to reproduce on the current build for both SADX and SA2.
