### ISSUE TITLE
[SADX] Low frame-rate in Save Select screen?

### ISSUE THREAD

**Issue by ViperAcidZX** [X-Hax/SA-Mod-Manager#116]
**Describe the bug**
I don't know if it's my PC having problems, but recently I am noticing some weird frame-rate problems in the Save Select menu for Sonic Adventure DX after using SADX Mod Installer with my Steam version of the game. I never had this issue before but lately whenever I go into the Save Select screen, the frame-rate drops to sub-30 FPS when it used to be able to run at full speed. I used the Dreamcast conversion preset and the issue persists.

**To Reproduce**
1. Perform a clean install of SADX on Steam.
2. Patch and downgrade the game to the 2004 version with SADX Mod Installer from PkR's website.
3. Launch the game after SADX Mod Installer has finished converting the game and installing mods.
4. Go to the Save Select screen after the Title Screen, frame-rate suddenly runs worse until the Main Menu appears.

**Expected behavior**
The game should be able to run at full 60 FPS in all areas despite how out-of-date my PC is since I never had this issue before, regardless of resolution or tweaks.

**Desktop (please complete the following information):**
Windows 10 Home (64-bit)
8 GB DDR3 RAM (@ 1600 MHz)
Nvidia GeForce GTX 1060 6 GB
AMD FX-4350 @ 4.2 GHz (4 cores)

**Additional context**
Latest d3d8to9 was also installed via SADX Mod Installer.

**Comment by Sora-yx** [comment]
Hello, 
I'd suggest to make sure your Mod Loader is up to date and uncheck "**Resizable Window**" if you have it enabled.
Either way, this is an issue in game, so this should be posted in the [Loader repo](https://github.com/X-Hax/sadx-mod-loader/issues) and not the Manager one. If your issue persist, please open the issue there.
