### ISSUE TITLE
[Feature Request] Allow adding own/custom codes

### ISSUE THREAD

**Issue by jroyvde** [X-Hax/SA-Mod-Manager#124]
**Describe the bug**
The current behaviour of the program when refreshing/updating the codes list seems to be to delete any codes added to Codes.lst by the user. I can understand this from the perspective of keeping the user's codes in sync with the latest ones provided by the devs, but there are definitely legit cases where a user would want to use codes that aren't (and probably shouldn't) be provided officially. For instance, I'm using the code written here:

https://gamebanana.com/posts/8545699

to work around an error in one of the mods I'm using. Given how specific and niche the purpose of this code is, I don't think it'd be a candidate for adding to the official database. But as a user I'd like to be able to keep using it, as well as having the developer-provided codes kept up-to-date.

**To Reproduce**
1. Add a code to Codes.lst
2. Refresh/update the codes list from inside the program

**Expected behavior**
It would be nice if there was a supported way for users to add and use their own codes. Maybe it'd make sense to keep them in a separate file from Codes.lst?

**Desktop**
 - OS: Fedora 39 with Proton Experimental
 - Version 1.2.8

**Comment by PiKeyAr** [comment]
You can add custom codes by providing your own Codes.lst in a mod. The main Codes.lst supplied by the Mod Manager is not supposed to be edited.

**Comment by ItsEasyActually** [comment]
Additionally when you create or edit a mod, the Edit Mod window has a Codes tab with a code editor built in, so you can add codes as needed without having to make the Codes.lst yourself. It also features syntax highlighting, and will verify codes before allowing the user to save them.

**Comment by jroyvde** [comment]
Cheers for the info! Since there's already a supported way to add custom codes I'll just go ahead and close this issue.

Would be nice to see this added to the wiki as well for anyone else who runs into the same confusion as me.
