### ISSUE TITLE
Mod updates: "Downloading file" label doesn't reset after switching to the next mod

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/SA-Mod-Manager#126]
**Describe the bug**
When multiple mod updates are being downloaded, the "downloading file" label displays files from the previous mod. This may have to do with mixing self-hosted and GitHub/GameBanana hosted mods. In addition, the "downloading file" label persists when there is no actual download (e.g. when the updater is parsing mod manifest).

**To Reproduce**
1. Update multiple mods

**Expected behavior**
Label resetting when an update for a different mod is being downloaded.

**Screenshots**
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/23312549/71f5d95d-39db-4cb4-b861-7be470fefd0b)
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/23312549/b87a1928-85e2-41fd-8f0f-265eab0e9435)

**Additional context**
The issue shown in the above screenshots occurred when there was an update for HD GUI 2 followed by an update for the Russian translation mod.

**Comment by Sora-yx** [comment]
Fixed in 1.2.9.
