### ISSUE TITLE
7z download fails, softlocking the app if Game Path is not Set

### ISSUE THREAD

**Issue by Sewer56** [X-Hax/SA-Mod-Manager#13]
**Describe the bug**
When installing the new Mod Manager, 7-zip download will fail if the game path is not set under `Manager Config`. 

**To Reproduce**
1. Launch Manager without 7zip Installed
2. Try to download 7-zip
3. .... wait, forever

**Expected behavior**
Manager auto detects game folder.

**Context**

This makes the first time experience sub-optimal.

The manager should ideally detect if it's placed in a supported game directory and auto configure itself.

**Comment by Sora-yx** [comment]
The game not being set was most likely not related to your issue, but either way, with the rework of how 7z is downloaded and installed on the last update, this should be fixed.
