### ISSUE TITLE
One Click Install not working for SA2

### ISSUE THREAD

**Issue by TheOldKingCole** [X-Hax/SA-Mod-Manager#132]
So I had initially download the old SA2 Mod Loader and it asked me if I wanted to switch to this mod loader and I did. The problem is the one click button on Game Banana still wants to output to the SA2 Modloader and thus when I use the One Click it does nothing.

**Comment by Sora-yx** [comment]
Try to click on "Uninstall mod loader" on the Manager Config tab, then "Install Mod Loader" it should enable one click install properly.

**Comment by Sora-yx** [comment]
Feel free to re open if the issue persist.
