### ISSUE TITLE
steam api.dll deletes itself when showing the mod manager its directory 

### ISSUE THREAD

**Issue by explosionenjoyer** [X-Hax/SA-Mod-Manager#134]
Please check the troubleshooting guide in the Wiki before submitting an issue.

As soon as I set the directory, the steam api.dll is deleted and copy pasting doesnt get it back, neither does moving a backup into the folder.

**To Reproduce**
1. Set directory
2. open the game in any way
3. See error

**Expected behavior**
The game opening like normal

**Screenshots**
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/162502420/b539ecd2-43be-406c-9cf8-a393b472868d)

**Desktop (please complete the following information):**
 - Windows: 
 - 11 

**Additional context**
when i DO have the api.dll, the game shows a 0xc0000906 error

**Comment by ItsEasyActually** [comment]
This isn't an issue with the Manager as it does nothing to this file. If you're having errors with this, your antivirus likely believes it to be a virus. 

Generally having issues with this file means you pirated the game as this file acts as DRM. We do not ensure things work with pirated copies, and we won't provide any assistance on making it work either.
