### ISSUE TITLE
[SA2] PS5 controller not working as Launcher is not bypassed

### ISSUE THREAD

**Issue by JimmyHedgehog** [X-Hax/SA-Mod-Manager#135]
When clicking Save and Play, the default Sonic Adventure 2 Launcher is brought up (Meaning I also have to reset resolution settings despite setting them in the Mod Manager), and since SA2 doesn't natively support the PS5 controller the Launcher doesn't detect a gamepad and force sets it to Keyboard.

I can go into the keyboard cfg file to manually change this, but this resets when the Launcher opens. 

Honestly just a way to bypass the launcher would solve this issue right away, is there a way to? As I cannot find one within the Mod Manager.

The old way would have been to rename sonic2app to Launcher, and rename the existing Launcher to something else, but the new Mod Manager seems to bring up errors and crash when the filenames are changed. Any way around this?

**Comment by Sora-yx** [comment]
When you click on Save and play, the Mod Manager starts the game directly (sonic2app.exe). If it starts the launcher, that means you still have the exe files renamed which you aren't supposed to, renamed exe is overall bad practice.

That said, if you want to bypass the launcher (like when starting the game from stream), you can add -q to the commands in Steam, that will bypass the launcher.

**Comment by JimmyHedgehog** [comment]
Oh huh, I could have sworn I'd reset them properly initially but it works now! I know that's generally bad practice anyway. Thanks for the info about the command to bypass it on steam though! That's handy to know. Thanks for answering my silly query
