### ISSUE TITLE
Borderless Windows (request, ignore if it's too bothersome)

### ISSUE THREAD

**Issue by Webardo** [X-Hax/SA-Mod-Manager#136]
Hi, is there a possibility to add a borderless window mode? My computer limits the clock speed when in fullscreen or in borderless fullscreen. so I'd rather have the option to have a windows with no borders. Thanks beforehand, sorry to bother.

**Comment by kellsnc** [comment]
So borderless fullscreen is just a borderless window that is the size of the screen. I find it odd that your computer would detect that as a fullscreen mode. You could use a tool like WinExplorer to remove borders yourself from a window. Or better, you could check your bios or vendor softwares to remove that limit?

**Comment by Webardo** [comment]
It's a laptop. It appears wattage is limited when fullscreen. Sadly there's no bios setting for that, but I can use Universal x86 Tuning Utility to manually set the power.

Thank you for answering!
