### ISSUE TITLE
Steam overlay is weird when opening mod manager

### ISSUE THREAD

**Issue by BroClub50** [X-Hax/SA-Mod-Manager#139]
![Screenshot 2024-05-16 171838](https://github.com/X-Hax/SA-Mod-Manager/assets/106852148/fa1486b8-c52a-4edc-a590-00c36e698248)
![Screenshot 2024-05-16 171825](https://github.com/X-Hax/SA-Mod-Manager/assets/106852148/a75fb6e9-e063-4540-92c5-980cf5217c18)
This is a visual bug that makes the steam overlay (and the fps overlay if you have it on) look weird and funny. It doesn't mess with the program's functionality.

How to reproduce the bug:
1. Click Play on SADX on steam.
2. Choose "Configure SADX" for launch option.
3. There it is!

Expected behavior:
Launcher looks normal
 
I am on Windows 11, the mod launcher version is 1.2.8.

**Comment by ItsEasyActually** [comment]
Just realized we never checked on this. Are you opening the Manager from Steam? If you are, that's why. This program isn't built with the idea of handling anything Steam may do, so we can't control if their overlay breaks from being enabled by launching the app through Steam.

**Comment by ItsEasyActually** [comment]
Closing this. If you happen to be able to provide more information, please reopen this issue.
