### ISSUE TITLE
Disabling a mod via the Keyboard Resets List Position

### ISSUE THREAD

**Issue by Sewer56** [X-Hax/SA-Mod-Manager#14]
**Describe the bug**

If you disable a mod by pressing the space button, the index of the currently selected item will be reset to 0. This means that if you're navigating the App through the keyboard, you will have to scroll the entire list again to disable another mod

**To Reproduce**
1. Go to Mods
2. Select a mod using the arrow keys on keyboard
3. Press 'Space' to enable/disable.
4. Cursor position resets to top of list when pressing up/down on keyboard.

**Expected behavior**
Cursor should stay at the previously selected item.

**Comment by Sora-yx** [comment]
Fixed in [b65152f](https://github.com/X-Hax/SA-Mod-Manager/commit/b65152fd782538f2544bbbcef80609fbfd7bb8ea)
