### ISSUE TITLE
Game crashes when playing with or without mods and cheats.

### ISSUE THREAD

**Issue by kingofcube** [X-Hax/SA-Mod-Manager#146]
**Describe the bug**
Launched the game with mods, it crashed, launched the game without mods, it crashed, cheats wasnt even enabled, how.

**To Reproduce**
1. Download mods and put them in the mods folder.
2. Install Mod Loader.
3. Launch game.
4. Game crashes.

**Expected behavior**
Actually launch the game with mods without crashes.

**Screenshots**
![SAModManager_LF1lLzePWj](https://github.com/X-Hax/SA-Mod-Manager/assets/138169081/6e5a4d48-0373-4a1f-8fc7-1aa2bf8cfa81)

**Desktop:**
 - OS: Windows 11.
 - Version 1.2.9.

**Additional context**
Yes, i have read the guide and tried every one, no, it didnt do anything to fix the problem. I even reinstalled SA2 two times and it still isnt fixed, hard-uninstalled the game and reinstalled it. (deleting the SA2 folder and redownloading it in Steam.) It did nothing.

Game is SA2 btw.

**Comment by kingofcube** [comment]
omfg i forgot this is bugs fuckkkkkk

**Comment by Sora-yx** [comment]
Games crashes with Loader installed are often related to lack of VC++ or just the game randomly crashing due to being a terrible port.
Either way, this issue is [Loader related](https://github.com/X-Hax/sa2-mod-loader/issues) and not Manager, so I'm closing this.

**Comment by PiKeyAr** [comment]
Isn't the loader checking the currently installed VC++ anyway?
