### ISSUE TITLE
If you search for a code then save when the search results are still visible, it'll deselect any codes that were previously enabled but weren't part of the search results.

### ISSUE THREAD

**Issue by Jesus-PK** [X-Hax/SA-Mod-Manager#15]
Something I randomly found, it only seems to happens with code search. Mod search appears unaffected by this. How to reproduce:

- Enable for example "Hide HUD".
- Ctrl + F in the codes section > Search for any keyword that will make Hide HUD not appear as search result (for example, "Disable").
- When the search results appears, simply save the current settings. It doesn't matter if you enabled any code or not.
- It'll deselect Hide HUD since it wasn't part of the search results.

**Comment by Sora-yx** [comment]
Fixed in [abbdbf5](https://github.com/X-Hax/SA-Mod-Manager/commit/abbdbf5e318bd1b784f607ad755cbfb3ca02f29d)
