### ISSUE TITLE
It recreates the Sonic Adventure directories as an example when creating a mod instead of Adventure 2 when Adventure 2 is selected in the mod manager

### ISSUE THREAD

**Issue by StupidGameridk** [X-Hax/SA-Mod-Manager#153]
**Describe the bug**
When you add a new mod while selecting Sonic Adventure 2, in my case adding a mod in the "Music" category and creating it recreates the directories for Sonic Adventure instead of Adventure 2. It also uses the information for Sonic Adventure for other categories too even if Adventure 2 is selected
**Adventure: mods\test\system\SoundData\bgm\wma
Instead of Adventure 2: gd_PC\ADX**

**To Reproduce**
1. Go to 'Add Mod' with 'Sonic Adventure 2' selected
2. Click on 'New Mod (For Developers)'
3. Fill in the required information for the mod, name, category in this case "Music"
4. Then, it will open the folder of the newly created mod and show that it's using the Sonic Adventure directory as the default reference

**Expected behavior**
It should recreate the directories for Sonic Adventure 2 instead of Sonic Adventure instead

**Screenshots**
![AqQOm5Acbb](https://github.com/X-Hax/SA-Mod-Manager/assets/125389741/6fe80c64-8a47-48bb-a7e5-fc31593ff684)
![qqAvqWJPeW](https://github.com/X-Hax/SA-Mod-Manager/assets/125389741/b7fb6f6b-24f4-4bea-871c-2998c2740c29)
![xSvu06VgOd](https://github.com/X-Hax/SA-Mod-Manager/assets/125389741/430e53e3-433e-43a4-8cce-a5eb46fe92b1)
![explorer_0pHyOqZnLv](https://github.com/X-Hax/SA-Mod-Manager/assets/125389741/c865ebd5-a7d8-4c21-97be-5b46ce6f3ca0)

Sonic Adventure music and sounds location for example
![explorer_F1RY1lFrO3](https://github.com/X-Hax/SA-Mod-Manager/assets/125389741/e5bc68d0-eb45-41bd-aafd-15723152b745)
Sonic Adventure 2 music location
![explorer_1rt8D4DkSY](https://github.com/X-Hax/SA-Mod-Manager/assets/125389741/c7529bb1-5c30-4364-aacd-5c120fcd85ac)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [Windows 7, 6.1, 7601]

**Comment by Sora-yx** [comment]
Thanks for the report, this will be fixed in the next update.
