### ISSUE TITLE
Mod Manager does not recognize dxvk d3d9.dll

### ISSUE THREAD

**Issue by PlateProp** [X-Hax/SA-Mod-Manager#157]
**Describe the bug**
Mod manager does not detect that DXVK is installed when placed in the same folder as "sonic2app.exe"

**To Reproduce**
Download DXVK via link in Mod Manager
Extract "d3d9.dll" from archive
Place "d3d9.dll" in the same directory as "sonic2app.exe"

**Expected behavior**
Mod manager should detect DXVK

**Screenshots**
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/10985577/12d79202-add6-43bc-8295-b62347c31841)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 22H2
 - OS Build: 19045.4529

**Additional context**
Tried both the x32 and x64 versions of DXVK. Additionally tried placing "d3d9.dll" into the Sonic Adventure DX directory, and it was still not detected.

**Comment by ItsEasyActually** [comment]
This isn't a bug. That feature is not implemented as a dependency thus the Mod Manager does not check for it. That message will be there regardless of you installing it or not.
