### ISSUE TITLE
Codes are updated even if none of the update checkboxes are checked

### ISSUE THREAD

**Issue by pkr-sadx** [X-Hax/SA-Mod-Manager#16]
This makes it difficult to test codes locally since the Mod Manager overwrites them on every startup.

Solution: Check for Codes updates only when checking for loader updates.

**Comment by ItsEasyActually** [comment]
You can create a mod that has your test codes then submit to the codes list once they have been tested. The Mod Manager also has a feature that makes it simple to add codes to a mod in the Edit Mod window. There isn't a reason to change the behavior as this solution is far simpler.

**Comment by Sora-yx** [comment]
Fixed in b13c29d8979ffdff0a7385cc6c8b63fb8998ddf3
Just fyi, if you are in debug mode, all the automatic update are disabled.

**Comment by pkr-sadx** [comment]
As of 1.0.5-befcc1f, Codes are still checked for updates on every startup, even if updates are disabled in the Manager.
