### ISSUE TITLE
what is this ??

### ISSUE THREAD

**Issue by jnwai** [X-Hax/SA-Mod-Manager#168]
[CrashDump_01_07_2024_17_32_26.dmp](https://github.com/user-attachments/files/16054401/CrashDump_01_07_2024_17_32_26.dmp)

**Comment by PiKeyAr** [comment]
Crash in Tails's main function. This repo if for SA Mod Manager bug reports, not for your individual mods, If you need help, ask on x-hax #troubleshooting channel.

**Comment by jnwai** [comment]
But i can't find his channel,can you leave a link for me
