### ISSUE TITLE
S key doesn't work properly in mod list

### ISSUE THREAD

**Issue by pkr-sadx** [X-Hax/SA-Mod-Manager#17]
**Describe the bug**
Using the S key to find mods that start with "S" in the mod list scrolls to the next mod.

**To Reproduce**
1. Highlight the mod list.
2. Press the S key.

**Expected behavior**
List should scroll to and highlight the mod whose title starts with "S"

**Comment by Sora-yx** [comment]
ce4c5d4af57ab114ac8d4e34e54a9b3244709cae
