### ISSUE TITLE
Crash with Game Directory

### ISSUE THREAD

**Issue by Lisandroa2010** [X-Hax/SA-Mod-Manager#170]
**Describe the bug**
The Mod Manager Crash after selecting The Game Folder.

**To Reproduce**
1. Go to Manager Config
2. Click on Game Directory
3. Select Choose Folder

**Expected behavior**
When i choose the Game Directory of SADX the mod manager Crash.

**Screenshots**
No Screenshots for this problem.

**Desktop**
 - OS: [Windows 11]
 - Version [23H2]

**Additional context**
the mod manager did not detect the game automatically.

**Comment by Sora-yx** [comment]
If the Manager crash you should have a crash dump with it, please share it.
