### ISSUE TITLE
Profiles not importing correctly

### ISSUE THREAD

**Issue by Semechko1** [X-Hax/SA-Mod-Manager#172]
**Describe the bug**
When I press "Import" on "Manage Profiles" screen, select new type of profiles (.json), they get correctly imported. But as soon as i exit this window and try to open them in main window, error pops up saying that they are not found. 

**To Reproduce**
1. Go to Manager Config
2. Open "Manage Profiles" window
3. Click on Import
4. Select your new profile that is not in C:\Users\[User]\AppData\Local\SAModManager\SADX (eg. it's on your Desktop)
5. Close "Manage Profiles" window
6. Select newly imported profile

**Expected behavior**
My new profile loads correctly either from directory I selected or it gets copied to app's special directory that contains them

**Screenshots**
![Знімок екрана 2024-07-11 141637](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/206eeb5f-a5d8-401f-94b8-29f96abf08d2)
![Знімок екрана 2024-07-11 141722](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/28511b20-726d-4832-9985-870b864c24f2)
![Знімок екрана 2024-07-11 141815](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/13baea9d-fdad-45bc-877c-3b97a401515d)
![Знімок екрана 2024-07-11 141845](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/6bf8858d-c497-47f0-b30b-3f225bef6acf)
![Знімок екрана 2024-07-11 142031](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/3f931f4f-4e80-48b5-ae3e-7571744f0850)

Screenshots should be in order showing the problem

 - OS: Windows 10
 - Version: ofc I'm running newest Mod Manager

**Comment by Sora-yx** [comment]
Thanks for the report, it was indeed an issue with a lack of copy of the profile. This is fixed in [6e73e4e](https://github.com/X-Hax/SA-Mod-Manager/commit/6e73e4e6e1b3633820dff83df8c085dd978d9b5f) and will be released on the next pubic update.
