### ISSUE TITLE
Request: Portable option

### ISSUE THREAD

**Issue by pkr-sadx** [X-Hax/SA-Mod-Manager#18]
I'd like to request an option that would enable the Manager's data to be stored in the Manager's EXE directory rather than `AppData\Local`.

Advantages:
1. The Manager's EXE and its settings/extlibs are all in one place.
2. If you put the Manager in the game folder, the game becomes portable. You could put it on a USB drive and play it on another computer with all your settings intact. This is something you could do with the old manager.

The implementation of this option would involve a simple check:
1. Check if there's a folder called `SAManager` in the same folder as the EXE.
2. If it exists, replace all variables using `AppData\Local\SAManager` to use `ExeFolder\SAManager`.

**Comment by kellsnc** [comment]
That could be a bonus if we wanna play SADX at work without leaving a trace 😋
Although I think portable should be a choice, not automatic by checking the exe. Maybe check for a folder named "SAManager" or a file ("portable.txt" in many softwares)

**Comment by pkr-sadx** [comment]
>Although I think portable should be a choice, not automatic by checking the exe. Maybe check for a folder named "SAManager" or a file ("portable.txt" in many softwares)

Yes, the folder check is what I suggested it in the implementation part.

**Comment by TCB13** [comment]
So, was this ever fixed? How do I run it in portable mode? Thanks.

**Comment by Sora-yx** [comment]
Yeah PkR implemented it. If you want to use the portable mode, simply copy the ``SAManager`` folder located in ``AppData\Local`` and put it where the SAModManager.exe is.

**Comment by TCB13** [comment]
> Yeah PkR implemented it. If you want to use the portable mode, simply copy the `SAManager` folder (located in `AppData\Local`) and put it where the SAModManager.exe is.

Thanks for the clarification, it does work :)
