### ISSUE TITLE
Add Extended Save Support toggle as a patch

### ISSUE THREAD

**Issue by pkr-sadx** [X-Hax/SA-Mod-Manager#19]
The toggle is already implemented on the Mod Loader's side. The value is `ExtendedSaveSupport`.

Patch name: Extended Save Support

Patch description: Enables support for saved games from the Steam version and allows custom save names (up to 48 characters).

In addition, while Test Spawn's save file selection still works for `SonicDX`-based filenames, it could be updated to pass the exact save filename in quotation marks (the Mod Loader has been updated to handle both cases).

**Comment by Sora-yx** [comment]
Done in feeaa51451952dcc257cf695c03df3bb8da552c4
