### ISSUE TITLE
Mod Loader Will Not Launch SA2

### ISSUE THREAD

**Issue by DrakkenWolfgang** [X-Hax/SA-Mod-Manager#192]
**Describe the bug**
When attempting to play SA2 via the Mod Manager, clicking "Save & Play" does not launch SA2. Mod Manager just reloads mods, patches, codes.

**To Reproduce**
1. Open Mod Manager
2. Select "Sonic Adventure 2" as game
3. Apply any codes, patches, graphical changes, etc
4. Click "Save & Play

**Expected behavior**
Mod Manager should launch SA2 when clicking "Save & Play."

**Desktop (please complete the following information):**
 - OS: Windows 11 Professional x64
 - Version 23H2
 - OS Build: 22631.4037

**Additional context**
While clicking "Save & Play" does not launch game (or state that anything is wrong or has crashed), manually running sonic2app.exe after clicking "Save & Play" with whatever Mod Manager changes (code enable/ disable, patch enable/ disable, graphical changes) seem to take effect. Manager itself just seems unable to launch the game itself. Have tried uninstalling both Manager & SA2, reinstalling both - same thing. Checked to make sure Mod Manager has correct path to game - it does. Not sure what may be causing this behavior.

**Comment by Sora-yx** [comment]
Can you try to re set the game location in the Manager Config tab to see if the issue persist?
Have you also tried to run the Manager as admin just in case?

**Comment by DrakkenWolfgang** [comment]
> Can you try to re set the game location in the Manager Config tab manually to see if the issue persist? Have you also tried to run the Manager as admin just in case?

Have checked/ reset game path multiple times - still won't launch from Mod Manager. Have also tried doing everything while running Mod Manager as Admin - Still won't launch game from Mod Manager.

**Comment by DrakkenWolfgang** [comment]
> Can you try to re set the game location in the Manager Config tab manually to see if the issue persist? Have you also tried to run the Manager as admin just in case?

Unintentionally marked as resolved/ closed. Have tried those things as well, issue still persists

**Comment by JustMLC4real** [comment]
running into the same issue here

**Comment by DrakkenWolfgang** [comment]
> running into the same issue here

Yeah... still not launching SA2.
I've tried completely removing mod manager & both SADX & SA2, reinstall only SA2, reinstall Mod Manager - game still won't launch from Mod Manager.

I have even gone as far as a clean install of Windows, then install SA2, then install Mod manager- still won't launch.

On my end, I think I've narrowed down possible cause. I think there is some bug in Mod Manager code that attempts to install manager correctly, yet fails to do correctly & it is only with SA2. SADX installs mod manager correctly for that game, but there is some underlying issue with the Manager install for SA2.

**Comment by ItsEasyActually** [comment]
Have you been attempting to launch the game with no mods installed at all? If so, that's the issue.

**Comment by nadoot1** [comment]
Having the exact issue myself. Not sure what to do to resolve it. I haven't attempted to launch the game without the mods.

**Comment by DrakkenWolfgang** [comment]
> Have you been attempting to launch the game with no mods installed at all? If so, that's the issue.
> 
> Edit: If you have been, that's the reason. It was a check that was returning true when it should have returned false. That has been fixed (no update released yet). Should be able to circumvent the issue in the interim by installing any mod regardless of if you're using it or not.
> 
> Please let us know if that was the issue so we can mark this accordingly.

Seems as though that was my issue. Added a mid & it started through "save & play." Thanjs for the help. Did not realize a mod had to be installed to launch game.

**Comment by nadoot1** [comment]
Would you mind sharing which mod you downloaded by chance? @DrakkenWolfgang :0

**Comment by DrakkenWolfgang** [comment]
> Would you mind sharing which mod you downloaded by chance? @DrakkenWolfgang :0

Chao World Extended, as it was the first to come to mind

**Comment by ItsEasyActually** [comment]
> Seems as though that was my issue. Added a mid & it started through "save & play." Thanjs for the help. Did not realize a mod had to be installed to launch game.

So funny thing, it's not meant to be required. it was an oops on our part with the previous update. it will be fixed in the next manager update, but this work around will fix it until the new update is out. Thanks for verifying it worked!

**Comment by nadoot1** [comment]
After the update, will we NEED a mod to launch the game? :O I didn't have any mods before and was able to launch it pre-update and hoping I can be able to do that again ;w;

**Comment by ItsEasyActually** [comment]
You won't! as mentioned, it was an accidental oversight that induced the bug, and the next update patches it, so it won't be an issue going forward.

**Comment by dylan-mcbee** [comment]
I am actually having this issue, and I do have mods enabled
