### ISSUE TITLE
modloader deleted some DirectX files when trying to install a mod

### ISSUE THREAD

**Issue by chasio2221** [X-Hax/SA-Mod-Manager#194]
Modloader deleted some DirectX files when trying to install a mod for sa2 "Chao World Extended"

**Comment by chasio2221** [comment]
little did I know I already have the mod installed so apparently the mod loader freaked out and deleted some files

**Comment by chasio2221** [comment]
now when I boot up sa2 I get this
![Screenshot 2024-08-19 235053](https://github.com/user-attachments/assets/676d11d3-fee7-4595-aff1-96dd88220955)

**Comment by chasio2221** [comment]
it deleted a lot of Windows .Dll files

**Comment by chasio2221** [comment]
like d3dx9_42.dll, vulkan-1.dll and MSVCR120.dll

**Comment by chasio2221** [comment]
now it's impossible to play sa2

**Comment by chasio2221** [comment]
I specially need help redownloading the files needed because reinstalling the sa2 did not help

**Comment by chasio2221** [comment]
sa1 works

**Comment by chasio2221** [comment]
but when on startup it does give me a couple errors saying that it's missing some libraries

**Comment by Sora-yx** [comment]
The Mod Manager doesn't delete any files, nor does it prevents the game to reinstall itself. Considering you mentioned Vulkan, you may have installed it and somewhat broke stuff with it. This could also be your antivirus not liking some of those DLL files (unlikely though). Anyway, If you want to reinstall properly SA2, uninstall it from Steam then delete the leftover files in the game directory, then and only then reinstall it.

This isn't related to the Manager itself so I'm closing this.
