### ISSUE TITLE
Typos in README & Wiki Troubleshooting Guide

### ISSUE THREAD

**Issue by ProximalElk6186** [X-Hax/SA-Mod-Manager#197]
1. In README file, section "Troubleshooting Guide", it says:

> If you are **experimenting** issues with the new Manager, please [check this guide](https://github.com/X-Hax/SA-Mod-Manager/wiki/Troubleshooting-Guide)

Maybe not "experimenting issues", but "experiencing issues"?
2. In Wiki Troubleshooting guide that it leads to, same typo at the end:

> If after reading everything above you're still **experimenting** issues, you can open [an issue here](https://github.com/X-Hax/SA-Mod-Manager/issues/new/choose) or on the [X-Hax Discord Server](https://discord.gg/gqJCF47) through the Troubleshooting section.

Same typo as in README.

**Comment by Sora-yx** [comment]
Good catch, should be fixed now
