### ISSUE TITLE
App Launcher Freezes When Trying to Change Controls

### ISSUE THREAD

**Issue by Pariah695** [X-Hax/SA-Mod-Manager#20]
To begin with, I was unable to change the controls at all. Using the App Launcher and changing inputs would not result in control changes in game, even though the settings were saved. I reinstalled SA1 and the mod manager from scratch, and that did not fix it.

To see if control changing was even working, I tried clearing the inputs for the A and X buttons to see what would happen. I tried to save, and the App Launcher crashed. It did still save the settings, but they still had not impact on the game.

Since then, the App Launcher began slowing down. Opening the controls page would show a black screen for a few seconds before displaying anything. And it crashes whenever I try to save control changes. And the initial black screen has gotten longer and longer each time I tried to save changes. Now it remains stuck on this black screen for an extremely long time. The app is unresponsive and crashes every time.

Deleting the App Launcher and folder to let the mod manager redownload it doesn't fix the problem.

**Comment by pkr-sadx** [comment]
Technically this issue isn't related to the Mod Manager because AppLauncher is a separate program. At some point in the future the new Mod Manager will have configurable controls in its UI, and AppLauncher will no longer be required.

**Comment by Pariah695** [comment]
Oh, sorry. Thanks for letting me know. Guess I'll wait on that update for now.

**Comment by pkr-sadx** [comment]
I don't know why the launcher would slow down or freeze (works fine here), but I can suggest a few things:
1. Make sure the launcher is up to date. Here's the latest version, extract it to your game folder: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/Setup/data/AppLauncher.7z
2. In the Mod Manager's Game Config page, make sure "Better Input (SDL2)" is selected in the Input tab.

**Comment by Pariah695** [comment]
Tried both. Neither fixed it.

**Comment by pkr-sadx** [comment]
Does your username have any non-ANSI characters in it? I found out that the extension I use in AppLauncher to write out INI files doesn't support Unicode, so it might break when writing to the user data folder where input configuration is stored.

A while back I developed my own INI extension that supports Unicode, so I'll be replacing the current one with it in the next launcher update.

**Comment by Pariah695** [comment]
My username is the same as it is here. Just Pariah695.

**Comment by Pariah695** [comment]
Tried replacing the dll. Didn't do anything.

I tried reinstalling the game and mod manager. I can open the AppLauncher again now. But it does not save my control settings, and every time I open the controls menu it's detecting my same controller as a new one.

**Comment by Pariah695** [comment]
The only path that seems odd is the startup path. It goes to Steam\steamapps\common\Sonic Adventure DX\

Not sure what that extra backslash at the end is for, or if that's even a problem. Everything else seems fine.

I forgot to mention, when I try to save my control changes or access the advanced control options, the launcher immediately closes.

**Comment by Pariah695** [comment]
The App Launcher is now working. I can save my controls and open the advanced options. But now we're back to the original problem. Even though my control changes are being saved, they are not taking affect in-game.

For the record, I'm trying to invert the camera controls for the free camera. I've also noticed that this whole time, the free camera is almost impossible to use. Unless I am extremely precise, the camera always moves diagonally.

**Comment by Pariah695** [comment]
Alright. Disabling the Input Mod fixed everything. Now it's working perfectly. Didn't change the deadzone. But now I can control the camera properly.

Thank you very much for all the help, pkr! And thanks so much for all the awesome stuff you and everyone here has done for this game!

**Comment by pkr-sadx** [comment]
Okay, I see what the problem was. The launcher saves settings for the Input Mod only as a legacy option when it can't find SA Manager's settings. I'll update it to also write the configuration for the Input Mod.

Thanks a lot for helping me resolve this.
