### ISSUE TITLE
Can't hit Save and Play? 

### ISSUE THREAD

**Issue by xCrazyVoidx** [X-Hax/SA-Mod-Manager#202]
Its greyed out and not able to be launched idk what to do 
![image_2024-09-07_030133784](https://github.com/user-attachments/assets/7f05ddb3-9e50-43e2-920f-298e3f24574a)

**Comment by Sora-yx** [comment]
Checkin Manager Config if the mod loader is installed, if it is try to re set the game location manually.

**Comment by xCrazyVoidx** [comment]
> Check in Manager Config if the mod loader is installed, if it is, try to re set the game location manually.

It didnt seem to change anything, i clicked the install mod loader and it just loads normally but Save and Play is still greyed out

**Comment by Sora-yx** [comment]
Did you use [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/index.php/download-sadx-mod-installer/)? If not I'd recommend using it.

**Comment by xCrazyVoidx** [comment]
> Did you use [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/)? If not I'd recommend using it.

Still no luck :/ idk i got the "Save and Play" to light up but it doesnt open the game

**Comment by xCrazyVoidx** [comment]
> Did you use [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/)? If not I'd recommend using it.

Wait, i think its working now I got the game to load now. How do I click multiplayer? Its greyed out currently, i completed Emerald Cost (first level)

**Comment by Sora-yx** [comment]
You need to progress more in the story or download a completed save file.
Either way, since this is working I'm closing the issue now.
