### ISSUE TITLE
meu app nao quer colocar o jogo do sonic adventure

### ISSUE THREAD

**Issue by souzarz** [X-Hax/SA-Mod-Manager#203]
Please check the troubleshooting guide in the Wiki before submitting an issue.

NOTE! This issue tracker is for bug reports for the SA Mod Manager only. This isn't a place to troubleshoot game crashes with your mods. If you need help with mods, please post on the x-hax Discord instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Sora-yx** [comment]
Cool story
