### ISSUE TITLE
All sound is absent and opening cinematic does not play

### ISSUE THREAD

**Issue by JohaknigIU** [X-Hax/SA-Mod-Manager#21]
After updating to the new mod loader, the game does not emit any sound whatsoever. The first boot this applied only to the background music with sound effects still playing, but now the game is completely silent. Volume is set to 100% on both windows and through the mod loader. The opening cinematic does not play either past the sega screen. Verified game files through steam and through the mod loader. Will completely wipe the install folder and reinstall Sonic Adventure, bettersaxd and the mod loader if the problem persists. Wanted to report here in case of issue with the loader.

**Comment by pkr-sadx** [comment]
For sounds and music, if you're coming from the Steam version make sure you have BASS enabled in the Mod Manager (Game Config page, Sound tab).

For videos, check if there are MPG files in your game's system folder. If you don't have them and only have SFD files, you need to get them either by using the SADX Mod Installer, which converts SFD videos to MPG, or by copying them from the old disc version of SADX (2004).

**Comment by Sora-yx** [comment]
Additionally, if after all the steps PkR mentioned it still doesn't work, try to re set the game path in the Manager Config tab, it will force a re install of the dependencies.

**Comment by JohaknigIU** [comment]
Thanks for the advice. Both of those steps were tried and still having no luck. I have removed all game files and reinstalled through steam, and will try reinstalling the mod loader to see if that fixes the problem. It might have been something on my end.

**Comment by JohaknigIU** [comment]
A fresh install on a different drive seemed to fix all my problems. Must have been a hard drive issue. Thank you both for your help.
