### ISSUE TITLE
SAModManager crashes when I open it

### ISSUE THREAD

**Issue by JBloom91** [X-Hax/SA-Mod-Manager#212]
As soon as I launch it I get an error message and the manager immediately closes afterwards.

**Comment by Sora-yx** [comment]
Hi, first of all you can try to delete that ``mods`` folder in the path that shows up on your screenshot since it's wrong as mods are in the games folder. If that folder doesn't exist at all, you can try to reset the settings of the Manager by deleting the SAManager folder in Appdata -> Local.

**Comment by JBloom91** [comment]
Thank you, I'll give it a try... If I can locate said folder lol I'll let you know if that works or not

**Comment by JBloom91** [comment]
Huh, that didn't work. I'll have to try again tomorrow, I'm dead tired.

**Comment by PiKeyAr** [comment]
Do you by any chance have a "SAManager" folder where SAModManager.exe is located?
