### ISSUE TITLE
Game crashes after selected stage

### ISSUE THREAD

**Issue by Danither3al** [X-Hax/SA-Mod-Manager#222]
Please check the troubleshooting guide in the Wiki before submitting an issue. 

**NOTE! This issue tracker is for bug reports for the SA Mod Manager only. This isn't a place to troubleshoot game crashes with your mods. If you need help with mods, please post on the x-hax Discord instead.**

Please stick to english and add as many details as possible.

**Describe the bug**
The game (Sonic Adventure 2) crashes when selecting a stage

**To Reproduce**
1. Click on "Save and play"
2. Chosse stage
3. Game crashes

**Expected behavior**
The game is supposed to play

**Screenshots**
 [proof](https://imgur.com/a/bmOgaCT)

**Desktop (please complete the following information):**
 - OS: Windos 11

**Comment by Sora-yx** [comment]
``This isn't a place to troubleshoot game crashes with your mods. If you need help with mods, please post on the x-hax Discord instead.``
