### ISSUE TITLE
Mod Manager: Check for MSVCRT versions.

### ISSUE THREAD

**Issue by GerbilSoft** [X-Hax/SA-Mod-Manager#223]
A common issue that causes SADX to crash when Mod Loader is installed is missing versions of the MSVC runtime. Since the SADX Mod Loader DLL is linked to the DLL runtime, this can't be detected at runtime, unless you wanted to make a stub DLL that was statically linked.

A better option would be to add MSVCRT scanning in the C# frontend:
* Set the C# frontend to x86 only. (It gains no advantage as amd64.)
* Check the System32 directory (Environment.SystemDirectory) for the following files:
  * 2010: msvcr100.dll
  * 2012: msvcr110.dll
  * 2013: msvcr120.dll
  * 2015/2017: vcruntime140.dll

Note that 2015/2017 use the same runtime.

If any are missing, provide download links:
* 2010 SP1: https://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe
* 2012 U4: https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe
* 2013 U5 + AVX fix: http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x86.exe
* 2015/2017: https://aka.ms/vs/15/release/vc_redist.x86.exe

**Comment by PiKeyAr** [comment]
I had to migrate to a different Windows installation recently and the Manager didn't offer to install any Visual C++ runtimes for me. Is this functionality actually implemented in the Manager?

**Comment by Sora-yx** [comment]
https://github.com/X-Hax/SA-Mod-Manager/blob/master/SA-Mod-Manager/Startup.cs#L71

**Comment by PiKeyAr** [comment]
Okay. So I can confirm that this doesn't work for VS2012 and VS2013, which are used by Smooth Camera and Idle Chatter mods.

**Comment by pkr-sadx** [comment]
Oct 13, 2024

Okay. So I can confirm that this doesn't work for VS2012 and VS2013, which are used by Smooth Camera and Idle Chatter mods.
