### ISSUE TITLE
"Maintain Mod Order" is malfunctioning

### ISSUE THREAD

**Issue by TheGamingSiri** [X-Hax/SA-Mod-Manager#227]
**Describe the bug**
Even after a mod is checked, moving and saving it will automatically return it to its alphabetical position. This contradicts the "Checked mods will no longer move when saving after checking them" message given when hovering over the option. This also occurs upon activating the toggle across all profiles without warning, eliminating any manual formatting that may have existed on a given profile.

**To Reproduce**
1. Check the "Maintain Mod Order" box on the "Manager Config" tab and save
2. Move to the "Mods" tab
3. Assuming your mods have not already been moved out of position, move any mod (checked or unchecked) and save again
4. Note the movement back to alphabetical

**Expected behavior**
I now realize that in my original request for this feature (https://github.com/X-Hax/SA-Mod-Manager/issues/86) I failed to note that the codes menu, which is always in alphabetical and can't be changed, never has to deal with this problem. For the mods list, however, the load hierarchy between mods often has to be different from alphabetical for compatibility reasons. Ideally, saving would not move any mods in the list at all, but instead maintain whatever manual hierarchy a given profile has employed regardless of what mods were checked/unchecked.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 64-bit
 - Version 1.3.0

**Additional context**
I do not blame any of the members of the team for this oversight; it was ultimately me who requested this feature initially, stated my case poorly, and met trepidation, I'll accept the consequences in this example as a monkey's paw. That said, PLEASE add a disclaimer ASAP letting people know what this feature currently does. I spent a good three hours between SA1 and SA2 creating manually sorted "All Mods On" profiles to keep track of my mods, which are now ruined. I can only assume I am not the only person who did this, and I can only imagine losing that will be as devastating for those folks as it's been for me.

**Comment by Sora-yx** [comment]
That's a known bug and it has been fixed on the dev build, update should be public soon, hopefully today.

**Comment by Sora-yx** [comment]
Should be fixed with the last update
