### ISSUE TITLE
The game crashes when i load green hill as tails (no mech)

### ISSUE THREAD

**Issue by ClassicSonicFan1** [X-Hax/SA-Mod-Manager#235]
Mod Loader API Version: 14
Use TestSpawn: Yes

[Full Message]
SA2 has crashed at 436ed6 (sonic2app.exe).

A crash dump, a mod list and a text file have been added to your game's CrashDumps folder.

If you want to report this crash, please include the dump (.dmp file), the mod list (.json file) and the info (.txt file) in your report.

[Mods]
Chao World Extended - 9.5.3.4
Enhanced Chao World - 1.4.1.3
 Choa Garden - Eggman
Extended Dark Garden - 1.0
Extended Neutral Garden - 1.5
Extended Hero Garden - 1.0
Chao Camera - 1.0
Chao Data Menu - 1.1.4.0
Chao Partner - 3.2.0
Character Select Plus - 1.5
Action Remap - 1.0
Better Radar - 1.2.0
Better Spinball fx - 
Cutscene Revamp - 1.1
Disable Upgrade Models - 
DJ SA2 - 1.2
Dreamcast Characters - 1.99
HedgePanel - 1.02
Menu Overhaul - 1.15
Physics Improvement - 1.0
SA2 Volume Controls - 1.5
Smooth Wall Colls V2 - 2.30
Sonic Adventure 2 Animated - 1.6
Super Sonic / Shadow - 3.0.1
Better Miles - 3.1.0

[Game Values]
GameMode: 14
GameState: 0
Current Level: 31
Last Level: 0
Current Character: 2

playertwp pointer was null.
(This is the crash dump btw)

**Comment by Sora-yx** [comment]
That is an issue with your mod list, this has nothing to do with the Manager or even the Loader.

**Comment by ClassicSonicFan1** [comment]
oh sorry i just don't know where to ask about mod problems
