### ISSUE TITLE
Reading Json Error when installed SADX Mod Installer

### ISSUE THREAD

**Issue by GamingUnleashed** [X-Hax/SA-Mod-Manager#252]
Hi, So I had this bug where it said Reading Jason Error & it just reset the mod manager idk why. I Installed SADX Mod Installer btw

**Comment by PiKeyAr** [comment]
This may be an issue with the installer. Try downloading the latest version of the mod installer and doing it again. If you still get the same error, please share the file Default.json located in Sonic Adventure DX\SAManager.

**Comment by PiKeyAr** [comment]
The installer has been updated with a fix. To fix it manually, In the file `Default.json` located in `Sonic Adventure DX\SAManager\SADX`, go to the following line:
`    "sadx-style-water,`
and change it to:
`    "sadx-style-water",`

If it still doesn't work, please upload your `Default.json`

**Comment by GamingUnleashed** [comment]
Alright Thank you so much I just reinstalled it again & double checked it & it worked fine after that
