### ISSUE TITLE
d3d8m.dll and SDL2.dll is deleted after updating SADXModLoader through mod manager

### ISSUE THREAD

**Issue by fsworld009** [X-Hax/SA-Mod-Manager#255]
**Describe the bug**

When I did a fresh installation with SADX Mod installer on the Steam version SADX, the mod loader works fine and can launch game with built-in mods.

However, when I open the mod manager, an update for SADXModLoader popup shows up (to version number 272a79d, at the time of writing). If I proceed the update, the following files are deleted after finishing the update (folders still exist):
1. path\to\Sonic Adventure DX\SAManager\extlib\SDL2\SDL2.dll
2. path\to\Sonic Adventure DX\SAManager\extlib\D3D8M\d3d8m.dll

As a result, the following features are broken in mod manager and mod loader:
1. Better Input (SDL2)
   * Launch the game would result in "Error loading SDL" error message and controllers won't work
2. Enable D3D8to9
   *  Checkbox is disabled in mod manager

If I backup these files first, and manually put them back after manager updates the loader, these features will work again.

**To Reproduce**
1. Download SADX from Steam
2. Install [SADX Mod Installer](https://sadxmodinstaller.unreliable.network/)
3. Verify `path\to\Sonic Adventure DX\SAManager\extlib\SDL2\SDL2.dll` and `path\to\Sonic Adventure DX\SAManager\extlib\D3D8M\d3d8m.dll` exist
4. Open mod manager
5. wait for the manager update popup and proceed update, or manually click manager update
6. `path\to\Sonic Adventure DX\SAManager\extlib\SDL2\SDL2.dll` and `path\to\Sonic Adventure DX\SAManager\extlib\D3D8M\d3d8m.dll` is deleted after the update

**Expected behavior**
Either the DLLs shouldn't be deleted after update, or the features shouldn't be broken.

**Screenshots**

![Screenshot_20241127_175606](https://github.com/user-attachments/assets/09376cd3-70e2-45d5-814e-30ebdebaee26)

**Desktop (please complete the following information):**
 - OS: Tried in both windows 11 and Linux with proton
 - Version 1.3.1

**Additional context**

I'm not sure if this is an issue with SA-Mod-Manager or SADXModLoader, but reporting here first, since I found this bug while using the mod manager. Please let me know in case I should move the issue to other places, thanks.

**Comment by PiKeyAr** [comment]
I think it's because recent commits to the Mod Manager repo have removed the files used to install these features due to a switch in the update system for an upcoming release. Since the files were removed but the new version isn't out yet, the current version fails to install them.

**Comment by PiKeyAr** [comment]
I put the files back and triggered a Mod Loader update, so it should work now after you check for updates.

**Comment by fsworld009** [comment]
Confirmed the files are added back in the latest update, thanks!

![Screenshot_20241127_190909](https://github.com/user-attachments/assets/2d07099e-1a17-4c18-a4ff-9ebf5af71993)
