### ISSUE TITLE
My mod manager keeps mods enable even though they aren't checked

### ISSUE THREAD

**Issue by dancaiman** [X-Hax/SA-Mod-Manager#257]
**Describe the bug**
After doing trying out some things with the manager (specifics in the context part) the game acted like mods that were unchecked were actually enabled

**To Reproduce**
1. Go to the manager in Sonic adventure 2
2. Check the maintain mod order in the advanced options
3.  Disable the skin selector mod, place the uekawa Sonic below it and check it
4. save and play, the game will have Sonic in his base model regardless of the uekawa mod being checked, and you will still have the skin selector interface even though the mod should not be activated

**Expected behavior**
After that, the manager will not disable any mod that you had when the bug occured, even though when you uncheck them all, This was solved by turning off my pc and turning it back on, but after trying it out for the second time (I wanted to see if the Uekawa mod by itself had the super sonic texture on it since when added to the skin selector mod it didn't) not even restarting and turning it off again worked

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I was trying out the skin selector mod by Sora, just to disable it and use the uekawa sonic mod as it separate mod, but then even though I unchecked the skin selector mod, the game acted like it was enabled and the uekawa mod enabled had no impact whatsoever, as in, Sonic was still his regular model, I was thinking this could also be because of the checked option of maintaining mod order like I mentioned on the steps, but it is the first time I use it so I don't know if it may be

https://github.com/user-attachments/assets/0a5a29a4-6914-4984-934e-2ddc4a4a2c14

![SONIC ADVENTURE 2 30_11_2024 22_16_38](https://github.com/user-attachments/assets/8c8de864-005a-40b6-9031-27f7de89195e)

![SONIC ADVENTURE 2 30_11_2024 22_16_45](https://github.com/user-attachments/assets/6f0fb6bf-d89c-4972-95db-912a52e36a86)

**Comment by ItsEasyActually** [comment]
This is related to the other issue you mentioned. The problem is your Mod Manager used to boot this is using the wrong settings compared to the game. Remove any SAManager folders in the same location as the SA Mod Manager executable, and the issue will be resolved. You may need to reset selected mods.
