### ISSUE TITLE
Auto updates for AppLauncher

### ISSUE THREAD

**Issue by pkr-sadx** [X-Hax/SA-Mod-Manager#26]
To check whether AppLauncher needs an update, the Manager could compare the file `AppLauncher.crc` with this one: https://dcmods.unreliable.network/owncloud/data/PiKeyAr/files/AppLauncher/AppLauncher.crc

If the file is different, it would do the same thing as the "Get AppLauncher" button does.

**Comment by Sora-yx** [comment]
Implemented with 1.1.6
