### ISSUE TITLE
The Game Is Not Opening Up After Installing New SA Mod Manager.

### ISSUE THREAD

**Issue by CristinaTheGamer** [X-Hax/SA-Mod-Manager#30]
Hi there, I was just reaching out because I previously used SADX Mod Manager for my game, which did work efficiently. However recently I received a notification on there stating that there will be a new upgraded Mod Manager, SA Mod Manager. After successfully installing the mod manager, I immediately noticed that after hitting "Save & Play", a small window would appear for a second before it closes. The game doesn't even attempt to launch. I have tried all I can at this point to problem solve the issue, but I don't know what's going on.

**Comment by Hypa-7** [comment]
For some reason when i opened SA mod manager and went to set the game directory it wouldn't detect sa2 even though its there in file explorer

**Comment by Sora-yx** [comment]
Did you rename sonic2app.exe?
