### ISSUE TITLE
FMV color bars

### ISSUE THREAD

**Issue by Flannels** [X-Hax/SA-Mod-Manager#34]
With the mod loader installed, all FMV cutscenes appear as TV static with color bars and no audio at all. This hasn't started happening until just now, so I have no idea what's causing this.

**Comment by Flannels** [comment]
I have the game running through Proton Experimental since that was part of the mod manager's install process. Could that be the problem?

**Comment by pkr-sadx** [comment]
Yes, most likely it is the problem. You could try a different version of Proton.


There is no official install process for SADX Mod Loader on Linux since neither the game nor the mod loader were designed to run on systems other than Windows. The main developers of the Mod Loader do not use Linux. The guides for getting the game or the mod loader to work on Linux and the Steam Deck are written by players, not developers, and they are not guaranteed to work. Even if they do, they may stop working after certain updates, although we try to avoid that when possible and when we're aware of it.

**Comment by Flannels** [comment]
Ok, I'll experiment with other versions of Proton and report back with my findings.

**Comment by Flannels** [comment]
So I went through and tried the other versions of Proton available and here's what I have:
- Most of the Protons seem to bust the mod manager, crashing the game upon attempting to open it
- None of the Protons fix the cutscenes, so I'm starting to get the impression that there's something wrong with the cutscene files. That's the only other answer I can think of because everything else in the game works without issue.

**Comment by Flannels** [comment]
I found a mod that replaces the FMVs with upscaled versions, I'll see if that works and report back.

**Comment by Flannels** [comment]
Update: it didn't work. I have no earthly idea what to do at this point.

**Comment by Flannels** [comment]
Should I try running a game health check?

**Comment by pkr-sadx** [comment]
The health check is not going to fix the problem. It will probably say that your FMV files have a wrong checksum, but that's expected for FMVs converted with the Mod Installer. They should still play fine.


I found a Discord thread reporting a similar problem a while back, here it is.
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/147223739/4732f7cd-a1b0-4965-86c9-ded01d4626e5)

**Comment by Flannels** [comment]
I'm trying to install proton 7.3 GE 1 but neither method I know of (protonup-qt and decky's wine cellar) will make it available. Am I doing something wrong?

**Comment by Flannels** [comment]
Like, I'm going into ProtonUp-qt and it's saying Proton-7.3-GE-1 is installed and is applied to SADX but then I open the Steam client and it either says no compatibility tool is applied, or a tool i could swear I didn't apply is being used instead, and Proton 7.3 GE 1 isn't showing up in the drop down menu so i can't just switch over

**Comment by Flannels** [comment]
and wine cellar won't even let me install 7.3 GE 1 at all. i'm trying REALLY hard to not lose my cool but this is making my head hurt.

**Comment by Flannels** [comment]
When i apply 7.3 GE 1 in protonup-qt, making sure the steam client is closed when i do so, steam then says the game has no compatibility tool applied and then won't let me launch the game at all. what am i doing wrong. im so tired.

**Comment by Flannels** [comment]
![ksnip_20231214-002923](https://github.com/X-Hax/SA-Mod-Manager/assets/104040055/c969a16f-4519-4e4d-b945-eb1dbcab58bb)
![ksnip_20231214-002830](https://github.com/X-Hax/SA-Mod-Manager/assets/104040055/5a419506-45bd-4c3b-a8ba-9d1a96904c95)
![ksnip_20231214-002647](https://github.com/X-Hax/SA-Mod-Manager/assets/104040055/09946f79-8dc2-4fee-80cf-f3a44a6cf4fb)

**Comment by Flannels** [comment]
I figured out how to actually get the version of proton installed and THE CUTSCENES WORK AGAIN!!!!! The only problem now is that the mod manager won't open with this proton but all that means is that I just have to switch back to experimental when i want to manage mods, then switch back when i want to play. Thanks for helping!
