### ISSUE TITLE
there seems to be problem with the audio

### ISSUE THREAD

**Issue by MarioLeo23** [X-Hax/SA-Mod-Manager#35]
https://gamebanana.com/tuts/16934

hello, I just downloaded the mods of Sonic Adventure following this guide, and I've had a problem with the settings. For some reason whenever I open Sonic Adventure and it opens the settings screen the sound settings keep going back to 1%, and it seems that even after I put it at any other percent it keeps coming back to 1% because when I open the game there is no sound, I then close the game, open the configuration again and it shows me sound at 1% even though I chose 100%. I'm not sure if this is the reason there is no sound but I know that it doesn't have to do with the use bass option because that one is checked, and I've already saved the settings, everything is saved BUT the sound settings which keep going back to 1%.

![Screenshot_20231216_083935](https://github.com/X-Hax/SA-Mod-Manager/assets/153995145/ad9eefee-6ba8-477b-befb-1bc14e5a93b5)

**Comment by PiKeyAr** [comment]
Hi, thanks for sharing this. I fixed the issue with the launcher, but this is a legacy screen that doesn't work with the new SA Mod Manager. If you're seeing it, you still have the legacy Mod Manager, which means you haven't completed the tutorial from step 7 onward.


To fix this, upgrade to the new SA Mod Manager and adjust sound volume in the Game Config/Sound tab.

**Comment by MarioLeo23** [comment]
Thanks for the help!!

I already did before commenting step 7 and step 8, I downloaded NET, updated it to sa mod manager and clicked on use bass, for some reason it still happens
![Uploading Screenshot_20231216_083935.png…]()

**Comment by MarioLeo23** [comment]
![Uploading Screenshot_20231216_100117.png…]()

**Comment by MarioLeo23** [comment]
Thanks for the help!!

I already did steps 7 and 8 before asking here, i downloaded NET, updated to sa mod manager, clicked on use bass and there's still no sound
![Screenshot_20231216_100627](https://github.com/X-Hax/SA-Mod-Manager/assets/153995145/01849401-9102-4b98-9d6a-89ed601aabb2)

**Comment by MarioLeo23** [comment]
hello, sorry for the mistake, I used the sadx mod manager they linked to in
gamebanana, I just found the one you listed in github

**Comment by MarioLeo23** [comment]
So, the mod manager is now version 1.0.5 and the old screen is gone, but there’s still no sound. I found someone who had the same issue three weeks ago (issue #21) and they fixed by installing everything on another drive. Should I do the same? What would you recommend?

**Comment by Semechko1** [comment]
> So, the mod manager is now version 1.0.5 and the old screen is gone, but there’s still no sound. I found someone who had the same issue three weeks ago (issue #21) and they fixed by installing everything on another drive. Should I do the same? What would be recommended?

Try reinstalling, because it's basically the same as installing somewhere else

**Comment by MarioLeo23** [comment]
Hello, I was busy and couldn’t speak for some time, I now have the current
mod loader, and I got the opening cinematic working, and there still is no
audio, toughts?

**Comment by PiKeyAr** [comment]
Make sure the volume is set correctly in the new Mod Manager, Game Config/Sound tab, and "Enable BASS for Music" and "Enable BASS for SFX" are enabled.


Other than that, there isn't much else to suggest besides the steps mentioned in the [troubleshooting guide](https://github.com/X-Hax/SADXModdingGuide/wiki/SADX-Troubleshooting-Guide#missing-music-andor-character-voices). We don't support platforms other than Windows, so if this is some kind of Steam Deck related problem, only other Steam Deck users can help you resolve it.

**Comment by MarioLeo23** [comment]
Oh well, I’ll need help somewhere else. Thank you for trying to help tough!

**Comment by MarioLeo23** [comment]
Oh well, I guess I’ll need help somewhere else, thanks for trying to help tough!

**Comment by amso71** [comment]
> Oh well, I guess I’ll need help somewhere else, thanks for trying to help tough!

i had this issue in the past, opening the original steam version’s config tool and enabling pulse audio fixed the issue for me
