### ISSUE TITLE
Persisting Crash in Super Sonic Story

### ISSUE THREAD

**Issue by DragonRanger199** [X-Hax/SA-Mod-Manager#36]
Sonic Adventure DX on Steam repeatedly crashes when playing the final Super Sonic section of the game. For whatever reason, the game cannot load Super Sonic's model/textures, and I receive an error message saying that the game failed to apply one or more textures. This has never been an issue for me with the previous SADX Mod Manager. It has only occurred using the new SA Mod Manager. The game will crash during the cutscene that introduces Super Sonic. Skipping the cutscene does not avoid the crash. I have tried various solutions to attempt to circumvent the issue, to no avail. 

I have provided a screenshot of my mod setup in SA Mod Manager for Sonic Adventure DX on Steam:

![Screenshot (83)](https://github.com/X-Hax/SA-Mod-Manager/assets/154037172/a458b1af-1b8d-4ab7-8fb0-8e46f19007ca)

**Comment by PiKeyAr** [comment]
I tried with the following mods I had at hand and it didn't crash:
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/23312549/816b6873-a51f-4380-bdf9-5f3b6c688adb)


I don't think the crash is related to the new Manager either way, so I think this should be closed.
