### ISSUE TITLE
Quick letter search doesn't work in Codes and Patches tabs

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/SA-Mod-Manager#37]
**Describe the bug**
As of Dev-1.1.0, using the keyboard to find codes or patches whose titles start with a specific letter doesn't work properly.

**To Reproduce**
1. Highlight the Codes or Patches list.
2. Press any key.

**Expected behavior**
The list should scroll to and highlight the code/patch whose title starts with the letter matching the pressed key.

**Comment by Sora-yx** [comment]
I only implemented quick letter search for mods, I don't plan to implement it for the rest, we have a functional search feature for mods and codes using CTRL + F, it's more than enough.
