### ISSUE TITLE
"Configure mod" crashes with Heroes Conversion

### ISSUE THREAD

**Issue by PiKeyAr** [X-Hax/SA-Mod-Manager#39]
Trying to open the [Heroes mod](https://gamebanana.com/mods/49969)'s configuration window crashes the Mod Manager. It works on the old SADX Mod Manager.

The error is `System.ArgumentException: ''0-General' is not a valid value for property 'Name'.'`

**Comment by Sora-yx** [comment]
Fixed in 0b4577287fcbb62f40fc298b462670e6390a24ce
