### ISSUE TITLE
Ukrainian translation crashes

### ISSUE THREAD

**Issue by Semechko1** [X-Hax/SA-Mod-Manager#40]
Please check the troubleshooting guide in the Wiki before submitting an issue.

**Describe the bug**
Whenever user select Ukrainian localization, Mod Manager wait for a while (1sec) and then closes, it also displays everything on English in that brief moment. If useer has Ukrainian as default, it will crash on startup with same 1 second of the window on english

**To Reproduce**
1. Switch to Ukrainian Locale in Settings

**Expected behavior**
Mod Manager displaying ukrainian language

Screenshot of before (v1.0.5)
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/00d5fef4-5406-4f59-8a31-3b9f430a7819)
Screenshot after (v1.1.0)
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/33aa2c04-c498-474f-b6f8-4dd4a208ed29)
Note that i can't do anything while it's in that moment, it's just frozen and crashes after a second

VS shows this (App.xaml.cs line 130):
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/96279531/a42f4a14-341f-448b-b46b-40a3497515ef)
And the Error message as .txt:
[message.txt](https://github.com/X-Hax/SA-Mod-Manager/files/13720113/message.txt)

Should be all, let me know if i forgot smth

**Comment by Sora-yx** [comment]
Fixed in ae2232e382878a10474136cf740f46ed1c65c17c
