### ISSUE TITLE
Intense SADX Stutter at all times in any resolution mode.

### ISSUE THREAD

**Issue by TailsGuy** [X-Hax/SA-Mod-Manager#45]
**Describe the bug**
SADX has a heavy stutter at all times during gameplay. This is in D3D8 and the D3D8to9 wrapper this and SADX Mod Loader came with. There were rumors of previous versions of D3D8to9 alleviating the stutter, but it's largely placebo. 

dxvk-gplasync and DXVK *do* have some effect on this, and there's much less stutter, however this is a workaround, not a fix. Even then there seems to be a hitch every second-two seconds as if there's a skipped frame. It's hard to record this phenomenon, so you'll have to check for yourself.

https://gitlab.com/Ph42oN/dxvk-gplasync
^ DXVK-gplasync, which I used. It's the latest asynchronous DXVK fork.

**To Reproduce**
All you really have to do is open up the game and play around for a couple of minutes. It's fairly noticeable.
For the DXVK wrapper put the d3d9.dll file in the 32x folder in the same directory as the executable.

**Expected behavior**
Ideally, no stutter. However this is probably a huge undertaking, so I wanted to bring this to light to at least have some discussion on the issue.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - [NVIDIA GeForce RTX 3070]
 
**Additional context**
I don't have a g-sync monitor, I'm running at full screen 1080p, as far as I know this persists at any resolution in any mode and with vsync off and on.

**Comment by PiKeyAr** [comment]
There's already [an issue](https://github.com/X-Hax/sadx-mod-loader/issues/124) about this on the Mod Loader repository. As far as we know, it's a problem with the vanilla game's framepacing. Since it isn't a bug in SA Mod Manager, I'm closing this.
