### ISSUE TITLE
Manager Crashes Consistantly Trying To Auto-Update Mods.

### ISSUE THREAD

**Issue by Pinkanator** [X-Hax/SA-Mod-Manager#49]
The update description is giving, begins download, tries to extract, then shuts down. Every time, without exception. This has applied to Lantern Engine and Tweaked Cutscenes mods specifically.

**Comment by Sora-yx** [comment]
This should be fixed with [the last update](https://github.com/X-Hax/SA-Mod-Manager/releases/latest). (I'd recommend installing it manually.)

**Comment by Pinkanator** [comment]
Yep, that's sorted it. Much obliged!
