### ISSUE TITLE
My SA1 game won't load with controller support anymore with the new mod loader

### ISSUE THREAD

**Issue by Bigctor4LIFE** [X-Hax/SA-Mod-Manager#63]
Whenever I try to load in SADX, it shows keeps on showing me this message, and I'm unsure what to do with it. (I'm not too good with tech rn). This applies for when I try to launch the game or

![image](https://github.com/X-Hax/SA-Mod-Manager/assets/158986085/22fc053a-6389-41f4-bea2-b075de8066ae)

I can run the game by clicking Save & Play but I'm forced to use keyboard controls. Is there anyway to get this fixed?

**Comment by Sora-yx** [comment]
Can you go into your SADX Folder and remove AppLauncher.exe as well as the folder with the same name? 
Then open the Manager, go to **game config** -> **input** tab and click on **"Get AppLauncher**". See if that fix it.

**Comment by Bigctor4LIFE** [comment]
Ohh, but that option is completely blocked off for me for some reason. It's faded out and I can't click on it

**Comment by Sora-yx** [comment]
If you can't click on **Get AppLauncher** that means it still detect it in the game folder so you probably didn't remove it.

**Comment by PiKeyAr** [comment]
This issue should be resolved since the Mod Manager now supports AppLauncher updates.
