### ISSUE TITLE
SDL Error and crash after update

### ISSUE THREAD

**Issue by Zombiesource2** [X-Hax/SA-Mod-Manager#7]
Game doesnt work anymore after update to new Mod Manager

![sdl_error1](https://github.com/X-Hax/SA-Mod-Manager/assets/125901786/4ae4c66b-d48f-4b8c-afa6-db8c75b165fd)
![crash1](https://github.com/X-Hax/SA-Mod-Manager/assets/125901786/95b1b7e2-743d-4148-94b3-74db001dac96)

CrashDump:
[CrashDump_18_11_2023_16_28_41.dmp](https://github.com/X-Hax/SA-Mod-Manager/files/13400574/CrashDump_18_11_2023_16_28_41.dmp)

**Comment by Sora-yx** [comment]
This should be fixed with the last Loader update.
