### ISSUE TITLE
Game File Keeps Getting Deleted while Installing the Launcher

### ISSUE THREAD

**Issue by NovaRaptorTV** [X-Hax/SA-Mod-Manager#78]
When I tried installing the mod manager for Sonic Adventure, it keeps deleting the game file. I am indeed using the steam version of Sonic Adventure DX, and I am unsure about how to recover the sonic.exe file if I am doing it correctly.

As for the install of the mod manager itself, I followed the top most option on the landing page, and set the install location to my D drive where I put most of my games. I drag sadx_setup and instdata to the same folder that the steam version of SADX is in. When I tried copying the sonic.exe file to attempt to get around this, the mod manager says I have to be using the 2004 version of the game.

**Comment by PiKeyAr** [comment]
This report has a lot of mixed up information but I'll try to respond to the best of my understanding.


> When I tried installing the mod manager for Sonic Adventure, it keeps deleting the game file.


If you're sure something is being deleted automatically, this is likely your antivirus interfering with loader installation.


>  I am indeed using the steam version of Sonic Adventure DX, and I am unsure about how to recover the sonic.exe file if I am doing it correctly.


You cannot install the Manager on the Steam version, and the Steam version doesn't have the sonic.exe file. Before you install the Manager, you need to convert the game to the old 2004 version using the Mod Installer (sadx_setup.exe).


>I followed the top most option on the landing page


What does this mean?


> set the install location to my D drive where I put most of my games


If this is about Manager installation, you should set the install location to the folder where your game is installed, not just the drive.


>  I drag sadx_setup and instdata to the same folder that the steam version of SADX is in.
> When I tried copying the sonic.exe file to attempt to get around this


You don't need to do either of that. Have you tried following any tutorials on how to get the Steam version modded?

**Comment by NovaRaptorTV** [comment]
Hi,

I wanted to clarify a couple of things.

1) "I followed the top most option on the landing page" For this I clicked the guided install
2) I will disable my antivirus to see if it helps
3) when I ran sadx_setup, it deleted sonic.exe during the install

Hope this clarifies a little more.

**Comment by NovaRaptorTV** [comment]
I also encountered another problem. I am unable to run sadx_setup.exe from the file that contains sonic adventure, but somehow I am able to run it if I double click it in winrar.

**Comment by NovaRaptorTV** [comment]
Disregard the previous statement. I extracted the files through 7Zip and it worked. However, after running sadx_setup, and then going back into SADX's folder on steam, I can confirm that the game itself got deleted.

**Comment by NovaRaptorTV** [comment]
if you want, I can send you the file after I had ran sadx_setup

**Comment by Sora-yx** [comment]
Considering this is more a problem with the installer than the manager I'm closing this.
