### ISSUE TITLE
Poblem with the new mod manager

### ISSUE THREAD

**Issue by Sonic01P1** [X-Hax/SA-Mod-Manager#8]
im not to access for my mods/codes/all setings help me ah and she asks me visual c++ 2013x86 (im with windows 11,x64) and downloaded but ask me again download visual c++ 2013 x86 :( Sorry for my bad english im from pais the lenguage spanish

**Comment by Sora-yx** [comment]
Hello, please [install the latest version here](https://github.com/X-Hax/SA-Mod-Manager/releases/latest) 
then follow the [Troubleshooting guide](https://github.com/X-Hax/SA-Mod-Manager/wiki/Troubleshooting-Guide)
If you're still experimenting issues, let me know.

**Comment by Sonic01P1** [comment]
wow thanks this mod loades is cool "xD"
