### ISSUE TITLE
Static Mod Hierarchy

### ISSUE THREAD

**Issue by TheGamingSiri** [X-Hax/SA-Mod-Manager#86]
**Describe the bug**
Perhaps "bug" isn't quite the right term for this, but I've noticed that the codes section and mods section behave differently and was wondering if parity between their behavior would be possible. Codes maintain a static placement in their list regardless of whether the code has been enabled or not. Mods, meanwhile, return all inactive mods to alphabetical order whenever they are saved as deselected. This makes mod organization needlessly difficult.

**To Reproduce**
1. Toggle a mod on
2. Save, note that the position is moved to the top of the hierarchy (or bottom of the mods hierarchy in the event other mods are already enabled)
3. Toggle a mod off
4. Save, note that the mod shifts back to its alphabetical position

**Expected behavior**
The mod would remain in the hierarchical position that it was left in after saving, regardless of whether the mod is on or off (just as a code would). An option to toggle between static and auto-alphabetical behavior for disabled mods would also be an effective resolution

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro - 64-bit
 - Version (1.1.6 - 8afdbf4)

P.S. Thank you for all of your hard work on this tool. This issue aside, it's been a joy to work with.

**Comment by ItsEasyActually** [comment]
After a lot of thought, this is way too complicated and definitely way more complicated than the existing system is.
