### ISSUE TITLE
"error occured when loading profiles" "object reference not set to instance of object"

### ISSUE THREAD

**Issue by Cay7809** [X-Hax/SA-Mod-Manager#89]
when opening mod manager, manager throws this error that an error occured and the object reference isnt set to an object instance

reproduce: go to profile and name it blank and try deleting it. after that, try closing the manager and open again

screen: 
![image](https://github.com/X-Hax/SA-Mod-Manager/assets/94752319/3790fea1-fd35-44db-b289-8a0ebafe882f)

 - OS: windows
 - Version: 10

**Comment by Sora-yx** [comment]
Thanks for the report, this will be fixed in the next update.

**Comment by Cay7809** [comment]
tks
