### ISSUE TITLE
The Game Won't Start

### ISSUE THREAD

**Issue by AaronStardust08** [X-Hax/SA-Mod-Manager#9]
I updated the AppLauncher, but the game still won't open with the SAModManager.  Do you know what to do?

**Comment by Sora-yx** [comment]
Make sure you have the last version of the Mod Manager and try to re set the game path so it will re install the Loader properly.

**Comment by AaronStardust08** [comment]
I did.  But it's still not working.

**Comment by AaronStardust08** [comment]
Never mind.  I figured out the problem.  I had to change the 4K setting to 1080p.  That's all.

**Comment by Sora-yx** [comment]
Glad you figured out.
Though, that sounds like there is a problem with graphic settings somewhere, so that should be examined. 
Thanks for the report.

**Comment by TBirdSoars** [comment]
Not sure if this is related, but attempting to run the game at anything higher than my native resolution (1440p) results in the game crashing, unless I select Fullscreen and check "Borderless Fullscreen" or play in Windowed mode.

**Comment by Sora-yx** [comment]
Well, I got confirmation that the crash when running the game at higher resolution in fullscreen is normal and was an issue on the previous loader version too. You most likely had one of the options quoted before enabled, which is why it was working fine. So I'm closing this.
